happeningSwitchTime: 180
nextHappeningShowTime: 10
spawnMobNum: 10
fallBlockNum: 3
teleportRange: 500
convertBlockRange: 4
womanPlayer:
  - 23zi_51hun
  - _hinana_
  - akenn1549
  - BALjirooo
  - Bro_Catherine
  - dbk_huuka
  - gin499
  - ikeko_99
  - kakikama
  - kono_a
  - n0r41nu
  - norunoru315
  - odisan_0723
  - Osaaaaa
  - rosec_pin
  - SAKIchan07
  - suzuki2929
  - urn1o
  - Yaci56
  - Yanyaa
  - YOSHIKO__CHAN__
  - onexttt0301
nonbinaryPlayer:
  - syakaijin_4869
  - Fnyantory
  - penny515
happening:
  - 'spawnPassiveMob'
  - 'spawnZombie'
  - 'spawnCleeper'
  - 'spawnEnderman'
  - 'spawnBat'
  - 'fallAnvil'
  - 'fallSand'
  - 'fallArrow'
  - 'fallMeteor'
  - 'changeFootBlockRandom'
  - 'changeFootBlockMagma'
  - 'changeFootBlockTNT'
  - 'addPlayerInvisible'
  - 'addPlayerLevitation'
  - 'addPlayerBlindness'
  - 'addPlayerRandomPotion'
  - 'addPlayerMoveSpeedUp'
  - 'addPlayerMiningSpeedUp'
  - 'addPlayerJumpPowerUp'
  - 'addPlayerPoison'
  - 'upgradeTool'
  - 'downgradeTool'
  - 'clearHotBarItem'
  - 'transHotBarItem'
  - 'teleportPlayer'
  - 'changePlayerDimension'
  - 'dieOnFootBlock'
  - 'beOneHp'
  - 'syncDeathEveryone'
  - 'syncDeathRandom'
  - 'beVeagan'
  - 'beCarnivore'
  - 'prohibitWater'
  - 'prohibitJump'
  - 'convertBlockToStone'
  - 'beSpongeBody'
  - 'prohibitMan'
  - 'prohibitWoman'